## Stage 1 Build Stage
# Node.js Image
FROM node:24-alpine AS build

# Setup of working directory
WORKDIR /app

# Copy the package.json file of the backend into the container and run it.
COPY package*.json ./
RUN npm install

# Copy the backend source code into WORKDIR
COPY . .

RUN npm run build

## Stage 2 nginx web server
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
